insert into classe (id, nome, tag, descricao) values (1, "Nomeação", "NOMEACAO", "Projetos referentes à nomeação de Ruas, Avenidas, Praças, Escolas, Creches, Hospitais etc.");
insert into classe (id, nome, tag, descricao) values (2, "Utilidade Pública", "UTILIDADE_PUBLICA", "Projetos de Declaração de Utilidade Pública.");
insert into classe (id, nome, tag, descricao) values (3, "Saúde", "SAUDE","Projetos relacionados à Saúde, como por exemplo destinação de verbas para hospitais ou pedido para uso de vacinas etc.");
insert into classe (id, nome, tag, descricao) values (4, "Acessibilidade", "ACESSIBILIDADE", "Projetos relacionados à Acessibilidade para PNEs.");
insert into classe (id, nome, tag, descricao) values (5, "Data comemorativa", "DATA_COMEMORATIVA", "Projetos de Proposta para criação de datas comemorativas, como o Aniversário da Cidade entre outros.");
insert into classe (id, nome, tag, descricao) values (6, "Educação e Cultura e Lazer", "EDUCACAO", "Projetos relacionados à Educação e Cultura e Lazer, como por exemplo inserir na grade curricular estudo sobre Cultura e Religião Africanas.");
insert into classe (id, nome, tag, descricao) values (7, "Outros", "OUTRO", "Projetos que não se encaixam em nenhuma das classficações.");
insert into classe (id, nome, tag, descricao) values (8, "Sem Classificação", "SEM_CLASSIFICACAO", "Projetos que ainda não foram classificados.");
insert into classe (id, nome, tag, descricao) values (9, "Causas Animais", "CAUSAS_ANIMAIS", "Projetos relacionados à Causas Animais e Animais Domésticos.");
insert into classe (id, nome, tag, descricao) values (10, "Manutenção", "MANUTENCAO", "Pedidos de manutação de Asfalto, UBS, Escola, Pintura, Troca de Lâmpadas, etc");
insert into classe (id, nome, tag, descricao) values (11, "Trânsito e Transporte", "TRANSPORTE", "Projetos relacionados à Trânsito e Transporte, como por exemplo duplicação de uma via, redução de velocidade de um determinado local, etc.");
insert into classe (id, nome, tag, descricao) values (12, "Segurança", "SEGURANCA", "Projetos relacionados à Segurança, como reforçar a frota policial entre outros.");
insert into classe (id, nome, tag, descricao) values (13, "Orçamento", "ORCAMENTO", "Projetos relacionados à aprovação de Orçamento para o ano, isenção para alguma instituição, etc.");
insert into classe (id, nome, tag, descricao) values (14, "Alteração de Lei", "ALTERACAO_LEI", "Projetos relacionados à Alteração de Leis.");
insert into classe (id, nome, tag, descricao) values (15, "Congratulação", "CONGRATULACAO", "Projetos relacionados à Congratulações, Felicitações, Moções de Aplausos, etc.");
insert into classe (id, nome, tag, descricao) values (16, "Meio Ambiente", "MEIO_AMBIENTE", "Projetos relacionados ao Meio Ambiente, como coleta seletiva, coleta de resíduos tóxicos, entre outros.");
insert into classe (id, nome, tag, descricao) values (17, "Urbanização", "URBANIZACAO", "Projetos relacionados à Urbanização, Lei de Zoneamento, como por exemplo Implantar Artifícios Arquitetônicos afim de inutilizar os bancos de praças");
insert into classe (id, nome, tag, descricao) values (18, "Consumidor", "CONSUMIDOR", "Projetos relacionados ao Consumidor, como por exemplo prazo para troca de produtos, etc.");
insert into classe (id, nome, tag, descricao) values (19, "Trabalho", "TRABALHO", "Projetos relacionados ao Trabalho, como deternminação de horas trabalhadas, e relacionado à projetos para servidores públicos.");
insert into classe (id, nome, tag, descricao) values (20, "Idoso", "IDOSO", "Projetos relacionados à Terceira Idade, determinação de prioridade em acentos de ônibus, atendimento em estabelecimentos comerciais etc.");
insert into classe (id, nome, tag, descricao) values (21, "Solicitação Médica", "SOLICITACAO_MEDICA", "Projetos relacionados à Solicitação Médica para pessoas físicas");

insert into partido_politico (id, sigla, nome) values (1, "PMDB", "PARTIDO DO MOVIMENTO DEMOCRÁTICO BRASILEIRO");
insert into partido_politico (id, sigla, nome) values (2, "PTB", "PARTIDO TRABALHISTA BRASILEIRO");
insert into partido_politico (id, sigla, nome) values (3, "PDT", "PARTIDO DEMOCRÁTICO TRABALHISTA");
insert into partido_politico (id, sigla, nome) values (4, "PT", "PARTIDO DOS TRABALHADORES");
insert into partido_politico (id, sigla, nome) values (5, "DEM", "DEMOCRATAS");
insert into partido_politico (id, sigla, nome) values (6, "PCdoB", "PARTIDO COMUNISTA DO BRASIL");
insert into partido_politico (id, sigla, nome) values (7, "PSB", "PARTIDO SOCIALISTA BRASILEIRO");
insert into partido_politico (id, sigla, nome) values (8, "PSDB", "PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA");
insert into partido_politico (id, sigla, nome) values (9, "PTC", "PARTIDO TRABALHISTA CRISTÃO");
insert into partido_politico (id, sigla, nome) values (10, "PSC", "PARTIDO SOCIAL CRISTÃO");
insert into partido_politico (id, sigla, nome) values (11, "PMN", "PARTIDO DA MOBILIZAÇÃO NACIONAL");
insert into partido_politico (id, sigla, nome) values (12, "PRP", "PARTIDO REPUBLICANO PROGRESSISTA");
insert into partido_politico (id, sigla, nome) values (13, "PPS", "PARTIDO POPULAR SOCIALISTA");
insert into partido_politico (id, sigla, nome) values (14, "PV", "PARTIDO VERDE");
insert into partido_politico (id, sigla, nome) values (15, "PTdoB", "PARTIDO TRABALHISTA DO BRASIL");
insert into partido_politico (id, sigla, nome) values (16, "PP", "PARTIDO PROGRESSISTA");
insert into partido_politico (id, sigla, nome) values (17, "PSTU", "PARTIDO SOCIALISTA DOS TRABALHADORES UNIFICADO");
insert into partido_politico (id, sigla, nome) values (18, "PCB", "PARTIDO COMUNISTA BRASILEIRO");
insert into partido_politico (id, sigla, nome) values (19, "PRTB", "PARTIDO RENOVADOR TRABALHISTA BRASILEIRO");
insert into partido_politico (id, sigla, nome) values (20, "PHS", "PARTIDO HUMANISTA DA SOLIDARIEDADE");
insert into partido_politico (id, sigla, nome) values (21, "PSDC", "PARTIDO SOCIAL DEMOCRATA CRISTÃO");
insert into partido_politico (id, sigla, nome) values (22, "PCO", "PARTIDO DA CAUSA OPERÁRIA");
insert into partido_politico (id, sigla, nome) values (23, "PODE", "PODEMOS");
insert into partido_politico (id, sigla, nome) values (24, "PSL", "PARTIDO SOCIAL LIBERAL");
insert into partido_politico (id, sigla, nome) values (25, "PRB", "PARTIDO REPUBLICANO BRASILEIRO");
insert into partido_politico (id, sigla, nome) values (26, "PSOL", "PARTIDO SOCIALISMO E LIBERDADE");
insert into partido_politico (id, sigla, nome) values (27, "PR", "PARTIDO DA REPÚBLICA");
insert into partido_politico (id, sigla, nome) values (28, "PSD", "PARTIDO SOCIAL DEMOCRÁTICO");
insert into partido_politico (id, sigla, nome) values (29, "PPL", "PARTIDO PÁTRIA LIVRE");
insert into partido_politico (id, sigla, nome) values (30, "PEN", "PARTIDO ECOLÓGICO NACIONAL");
insert into partido_politico (id, sigla, nome) values (31, "PROS", "PARTIDO REPUBLICANO DA ORDEM SOCIAL");
insert into partido_politico (id, sigla, nome) values (32, "SD", "SOLIDARIEDADE");
insert into partido_politico (id, sigla, nome) values (33, "NOVO", "PARTIDO NOVO");
insert into partido_politico (id, sigla, nome) values (34, "REDE", "REDE SUSTENTABILIDADE");
insert into partido_politico (id, sigla, nome) values (35, "PMB", "PARTIDO DA MULHER BRASILEIRA");

insert into tipo (id, nome, descricao) values (1, "Projeto de Lei", "Proposta por um(a) vereador(a) ou pela Prefeitura, visa criar nova lei ou alterar leis já existentes. Discutida na Câmara, poderá ser aprovada ou rejeitada.");
insert into tipo (id, nome, descricao) values (2, "Projeto de Decreto Legislativo", "Projeto destinado a disciplinar assuntos que excedam ao âmbito da Câmara, tais como fixação de subsídios e aprovação das contas da Prefeitura. Este independe de sanção do prefeito.");
insert into tipo (id, nome, descricao) values (3, "Projeto De Emenda À Lei Orgânica Municipal", "Projeto que visa alterar a Lei Orgânica Municipal (a “Constituição” do Município). Também exige quórum qualificado.");
insert into tipo (id, nome, descricao) values (4, "Requerimento", "Instrumento de fiscalização, é apresentado por vereador(a) e tem por objetivo solicitar informações a Prefeitura ou a algum outro órgão público, acerca da gestão, investimentos ou políticas públicas.");
insert into tipo (id, nome, descricao) values (5, "Projeto de Lei Complementar", "Da mesma forma que o projeto de lei, visa criar uma nova lei ou alterar lei já existente. Exige quórum qualificado (mais votos) para sua aprovação.");
insert into tipo (id, nome, descricao) values (6, "Projeto de Resolução", "Projeto destinado a disciplinar assuntos internos da Câmara, tais como política administrativa, de pessoal, alteração do Regimento Interno e outros.");
insert into tipo (id, nome, descricao) values (7, "Indicação", "Instrumento através do qual o(a) vereador(a) sugere ou solicita a Prefeitura a realização de determinados serviços públicos.");
insert into tipo (id, nome, descricao) values (8, "Moção", "Proposta apresentada por vereador(a) congratulando-se ou repudiando atitudes ou ações de pessoas ou entidades ou ainda manifestando condolências.");
insert into tipo (id, nome, descricao) values (9, "Diversos", "");

insert into situacao_simplificada (id, nome, descricao) values (1, "Em tramitação", "São os processos que ainda não foram apreciados pelo plenário.");
insert into situacao_simplificada (id, nome, descricao) values (2, "Aprovado", "São os processos que obtiveram maioria de voto no plenário.");
insert into situacao_simplificada (id, nome, descricao) values (3, "Arquivado", "São os processos que foram retirados pelo autor ou rejeitados pelo plenário que não obtiveram a maioria de votos suficientes para a sua aprovação.");
insert into situacao_simplificada (id, nome, descricao) values (4, "Rejeitado", "São processos rejeitados");
insert into situacao_simplificada (id, nome, descricao) values (5, "Sem Situação", "Processo antigo sem situação cadastrada");